-- Create a new database called 'INFRAESTRUCTURA'
-- Connect to the 'master' database to run this snippet
USE master
GO
-- Create the new database if it does not exist already
IF NOT EXISTS ( SELECT [name] FROM sys.databases WHERE [name] = N'INFRAESTRUCTURA')
    CREATE DATABASE INFRAESTRUCTURA
GO

DECLARE
    @KEYPROVADA NVARCHAR(128) = '~CCKrWUrwy9Z4X2jDBl|',
    @MENSAJE NVARCHAR(MAX) = 'MARIA LUISA CASTRO TONCEL',
    @DESENCRIP NVARCHAR(MAX),
    @ENCRIPT VARBINARY(8000)
SET @ENCRIPT = ENCRYPTBYPASSPHRASE(@KEYPROVADA,@MENSAJE)
SET @DESENCRIP = CONVERT(NVARCHAR, DECRYPTBYPASSPHRASE(@KEYPROVADA,@ENCRIPT))
SELECT @DESENCRIP AS DESEMCRIPTADO, @ENCRIPT AS ENCRIPTADO
