USE [INFRAESTRUCTURA]

-- Eliminamos la Tabla si esta Existe
IF OBJECT_ID('[dbo].[DOMINIO]', 'U') IS NOT NULL
DROP TABLE [dbo].[DOMINIO]
GO

-- Creamos la Tabla Dominio
CREATE TABLE [dbo].[DOMINIO]
(
    IDDOMINIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CODIGO AS ('DM' + RIGHT ('0000' + CONVERT(VARCHAR,IDDOMINIO),(4))),
    NOMBRE VARCHAR(150) NOT NULL,
    USUARIO VARCHAR(100) NOT NULL,
    CONTRASENA VARCHAR(150) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
GO

-- Eliminamos el Procedimiento Almacenado de Listar Dominios si este existe
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_SCHEMA = N'dbo' AND SPECIFIC_NAME = N'LISTAR_DOMINIOS' AND ROUTINE_TYPE = N'PROCEDURE')
    DROP PROCEDURE dbo.LISTAR_DOMINIOS
GO

-- Listar Todos los Dominios existentes
CREATE PROCEDURE dbo.LISTAR_DOMINIOS
AS
BEGIN
    SELECT * FROM [dbo].[DOMINIO]
END
GO

-- Eliminamos el Procedimiento Almacenado de Listar Dominio Segun Id y Codigo si este existe
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_SCHEMA = N'dbo' AND SPECIFIC_NAME = N'LISTAR_DOMINIO' AND ROUTINE_TYPE = N'PROCEDURE')
    DROP PROCEDURE dbo.LISTAR_DOMINIO
GO

-- Listar Dominio Segun Id y Codigo Enviado
CREATE PROCEDURE dbo.LISTAR_DOMINIO
    @IDDOMINIO INT,
    @CODIGO VARCHAR(6)
AS
BEGIN
    SELECT * FROM [dbo].[DOMINIO] WHERE IDDOMINIO = @IDDOMINIO AND CODIGO = @CODIGO
END
GO


-- Eliminamos el Procedimiento Almacenado de Insertar Dominios si este existe
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_SCHEMA = N'dbo' AND SPECIFIC_NAME = N'INSERTAR_DOMINIO' AND ROUTINE_TYPE = N'PROCEDURE')
    DROP PROCEDURE dbo.INSERTAR_DOMINIO
GO

-- Creamos Procedimiento Almacenado de Insertar
CREATE PROCEDURE dbo.INSERTAR_DOMINIO
    @NOMBRE VARCHAR(150),
    @USUARIO VARCHAR(100),
    @CONTRASENA VARCHAR(150),
    @RESULTADO INT OUTPUT,
    @ID INT OUTPUT
AS
BEGIN
    IF EXISTS (SELECT * FROM [dbo].[DOMINIO] WHERE USUARIO = @USUARIO)
    BEGIN
        SELECT * FROM [dbo].[DOMINIO] WHERE USUARIO = @USUARIO
        SELECT @ID = IDDOMINIO FROM [dbo].[DOMINIO] WHERE USUARIO = @USUARIO
        SET @RESULTADO = -1 -- USUARIO YA EXISTE CON EL CODIGO
    END
    ELSE
    BEGIN
        INSERT INTO [dbo].[DOMINIO] ( [NOMBRE], [USUARIO], [CONTRASENA] ) VALUES ( @NOMBRE, @USUARIO, @CONTRASENA )
        SET @ID = SCOPE_IDENTITY()
        SET @RESULTADO = 0 -- SE INSERTA EL USUARIO
        SELECT * FROM [dbo].[DOMINIO] WHERE IDDOMINIO = @ID
    END
END
GO


--Eliminamos el Procedimiento Almacenado de Actualizar Dominios si este existe
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_SCHEMA = N'dbo' AND SPECIFIC_NAME = N'ACTUALIZAR_DOMINIO' AND ROUTINE_TYPE = N'PROCEDURE' )
    DROP PROCEDURE dbo.ACTUALIZAR_DOMINIO
GO

-- Creamos Procedimiento Almacenado de Actualizar
CREATE PROCEDURE dbo.ACTUALIZAR_DOMINIO
    @IDDOMINIO INT,
    @NOMBRE VARCHAR(150),
    @USUARIO VARCHAR(100),
    @CONTRASENA VARCHAR(150),
    @RESULTADO INT OUTPUT
AS
BEGIN
    IF NOT EXISTS(SELECT * FROM [dbo].[DOMINIO] WHERE IDDOMINIO = @IDDOMINIO)
    BEGIN
        SET @RESULTADO = -1 -- EL USUARIO A ACTUALIZAR NO EXISTE
    END
    ELSE
    BEGIN
        DECLARE @CREATE_UP DATETIME = CURRENT_TIMESTAMP
        UPDATE [dbo].[DOMINIO] SET NOMBRE = @NOMBRE, USUARIO = @USUARIO, CONTRASENA = @CONTRASENA, UPDATED_AT = @CREATE_UP WHERE IDDOMINIO = @IDDOMINIO
         SET @RESULTADO = 0 -- SE ACTUALIZO CORRECTAMENTE
    END
    RETURN @RESULTADO
END
GO
