USE [INFRAESTRUCTURA]

--Seleccionamos las Filas de la Tabla '[DOMINIO]'
SELECT * FROM [dbo].[DOMINIO]
GO

-- Insertamos Filas en la Tabla 'DOMINIO'
INSERT INTO [dbo].[DOMINIO] ( [NOMBRE], [USUARIO], [CONTRASENA] ) VALUES ( 'JOSE CASTRO CANTILLO', 'JCASTRO', 'CONTRASEÑA')
GO

--Ejecutar listar Dominios
EXECUTE [dbo].[LISTAR_DOMINIOS]

--Ejecutar listar Dominio Segun ID y Codigo
DECLARE 
    @CODIGO VARCHAR(6) = 'DM0002',  
    @IDDOMINIO INT = 2
EXECUTE [dbo].[LISTAR_DOMINIO] @IDDOMINIO, @CODIGO


-- Ejecutamos Procedimiento Almacenado
DECLARE 
    @NOMBRE VARCHAR(150) = 'MARIA CANTIGO GONZALEZ',
    @USUARIO VARCHAR(100) = 'MCANTILLO',
    @CONTRASENA VARCHAR(150) = 'CONTRASEÑA',
    @RESULT INT
EXECUTE [dbo].[INSERTAR_DOMINIO] @NOMBRE,@USUARIO,@CONTRASENA, @RESULT OUTPUT
PRINT @RESULT
GO

-- Ejecutamos Procedimiento Almacenado
DECLARE 
    @IDDOMINIO INT = 3, 
    @NOMBRE VARCHAR(150) = 'MARIA CANTIGO GONZALEZ', 
    @USUARIO VARCHAR(100) = 'MCANTILLO', 
    @CONTRASENA VARCHAR(150) = 'CONTRASEÑA', 
    @RESULT INT;
EXECUTE [dbo].[ACTUALIZAR_DOMINIO] @IDDOMINIO,@NOMBRE,@USUARIO,@CONTRASENA, @RESULT OUTPUT
PRINT @RESULT
GO


 SELECT @@IDENTITY AS 'Identity';